title: DokuGaku Nihongo | Aprende Japonés Gratis y Prepárate para el JLPT N5-N1

description: >
  Aprende japonés gratis desde el nivel N5 hasta el N1.
  Encuentra ejercicios, gramática, kanjis, listening, simulacros
  del JLPT y recursos para estudiar japonés autodidacta.

url: https://dokugakunihongo.github.io

lang: es

google_analytics: G-VS5JBFQPTE

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
